# Generated by Django 5.0.4 on 2024-05-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoproject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
